# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 529f8cb04dd9fff8b65549dca654abb321eb5bc3cf2d2566eadbe36548197ca98945fb1d2e87ac5fa2dcc4e885230beaeb0dde7024e4ebcd148edb5fc838836e

test:
  secret_key_base: b8b3b96a1bfc83e417780080ef295d0698b5cd53ca73f3180860442b1a8ce3ed63f77509e5109a462bf1fb4c2895f96cf1f29240e5f890ee7eeb7624cd899c81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
